graphhopper:
  datareader.file: /data/busan.osm.pbf
  graph.location: /data/graph-cache
  custom_models.directory: /config/custom_models
  graph.encoded_values: foot_access,foot_average_speed
  profiles:
    - name: visual_safe
      custom_model_files: [visual_safe.json]
    - name: visual_fast
      custom_model_files: [visual_fast.json]
    - name: wheelchair_safe
      custom_model_files: [wheelchair_safe.json]
    - name: wheelchair_fast
      custom_model_files: [wheelchair_fast.json]
  profiles_ch: []
  profiles_lm:
    - profile: visual_safe
    - profile: visual_fast
    - profile: wheelchair_safe
    - profile: wheelchair_fast
  prepare.lm.landmarks: 16
  import.osm.ignored_highways: motorway,trunk
  graph.dataaccess.default_type: RAM_STORE

server:
  application_connectors:
    - type: http
      port: 8989
  admin_connectors:
    - type: http
      port: 8988
  request_log:
    appenders: []
